# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72d708284df3d1081a5b3138797ba0a88a39d98933963f0004d2c548ee76e6102e23f923e968993de1c98c4d4e657b3f148143e176d41d994176da83f104d923

test:
  secret_key_base: f39d7caa3fa8872a4420f35c151852d96926d14995bf0349dd11b85d624ef6e596ee225d9b3074fa048818ceda54f4ffd02f749454a564d46b6d153d586cde4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
